# use a workflow run to watch for a PR, download the PR artifact and trigger a sonar scan

name: Run Sonar Scan

on:
  workflow_run:
    workflows: ["Receive PR"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download PR artifact
        uses: actions/download-artifact@v2
        with:
          name: pr
          path: pr/

      - name: Run Sonar Scan
        uses: sonarsource/sonar-scan-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: pr
          extraProperties: |
            sonar.pullrequest.key=${{ github.event.workflow_run.pull_requests[0].number }}
            sonar.pullrequest.branch=${{ github.event.workflow_run.pull_requests[0].head.ref }}
            sonar.pullrequest.base=${{ github.event.workflow_run.pull_requests[0].base.ref }}

