# use a workflow run to watch for a PR, download the PR artifact and trigger a sonar scan

name: Run Sonar Scan

on:
  workflow_run:
    workflows: ["Receive PR"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      # download the PR artifact
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Downlod Artifacts 
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}
        
      - name: Unzip PR artifact
        run: unzip pr.zip
      # run sonar scan
      - name: Sonar Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

