# use a workflow run to watch for a PR, download the PR artifact and trigger a sonar scan

name: Run Sonar Scan

on:
  workflow_run:
    workflows: ["Receive PR"]
    types:
      - completed
  push:
    branches:
      - main

jobs:
  build-PR:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Downlod Artifacts 
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}
        
      - name: Read PR number
        run: |
          cat ./pr/NR
          echo "PR_NUMBER=$(cat ./pr/NR)" >> $GITHUB_ENV
      # checkout the PR
      - name: Checkout PR
        uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ env.PR_NUMBER }}/merge
          fetch-depth: 0
      # print pull request data for sonar
      - name: Print PR data
        run: |
          echo "PR_NUMBER=${{ env.PR_NUMBER }}"
          echo "PR_BRANCH=${{ github.event.pull_request.head.ref }}"
          echo "PR_BASE=${{ github.event.pull_request.base.ref }}"
      # run sonar scan
      - name: Sonar Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
              -Dsonar.pullrequest.key=${{ env.PR_NUMBER }}
              -Dsonar.pullrequest.branch=${{ github.head_ref }}
              -Dsonar.pullrequest.base=${{ github.base_ref }}

  build-main:
    runs-on: ubuntu-latest
    # if the workflow run is not a PR, run a normal scan
    if: >
      github.event_name == 'push' &&
      github.event.workflow_run.event != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sonar Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

